[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs run --chip RP235x"
rustflags = ["-C", "link-arg=-Tlink.x", "-C", "link-arg=-Tdefmt.x"]

[target.'cfg(all(target_arch = "riscv32", target_os = "none"))']
runner = "probe-rs run --chip RP235x"
rustflags = ["-C", "link-arg=-Trp235x_riscv.x", "-C", "link-arg=-Tdefmt.x"]

[build]
target = "thumbv8m.main-none-eabihf"
